### ISSUE TITLE
Problem compiling Arduplane 2.76 for Crius v1....

### ISSUE THREAD

**Issue by sykick** [smurfy/ardupilot-mpng#1]
When I select Crius V1 and try to compile I get error msg's about dataflash. I'm pretty sure the Crius V1 does not have dataflash, so how do you disable this so Arduplane 2.76 will compile? I checked Arducopter and this will compile fine with the same board selected.

Many thanks,
Sykick

**Comment by smurfy** [comment]
Fixed the problem. (needed to merge an old fix i already done for 0.74b)

**Comment by sykick** [comment]
Thanks Smurfy for the quick fix, I'll give it another go....

rgds,
Sykick
