### ISSUE TITLE
crius v2 wont recognice by mission planner after arduplane 2.76

### ISSUE THREAD

**Issue by vargasesteban** [smurfy/ardupilot-mpng#3]
Hi , I am trying to fix a compass problem , my crius V2 from RC timer is not detecting the Compass when i power the crius from ESC , but when i connect it to the USB it work .
I download the source project (https://github.com/smurfy/ardupilot-mpng/archive/mpng_ArduPlane-2.76.zip) but when i use the arduino software with the JAR file , the mission don't connect to the crius .
I check the crius mounting the Arducopter software with arduino , and work perfect .
 also use the Flashing tool and IT work the mission star to get mavlink communication , but still have the BAD COMPASS HEALTH , and the compass is disable by it self

**Comment by smurfy** [comment]
In arduplane, gyro, accel recalibriate on every startup. make sure you have the board plan for around 30 seconds until its fully booted. you can also reset the eeprom, that helps most of the time.

**Comment by vargasesteban** [comment]
are you working on the new arduplane version ?
thanks for your work.
